### ISSUE TITLE
ProductProjection Search POST request

### ISSUE THREAD

**Issue by D1mitry** [commercetools/commercetools-dotnet-core-sdk-v2#100]
**Describe the bug**
`Post(JsonElement? jsonNode)` method of the [ByProjectKeyProductProjectionsSearchRequestBuilder](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Sdk.Api/Generated/Client/RequestBuilders/ProductProjections/ByProjectKeyProductProjectionsSearchRequestBuilder.cs)  class has `jsonNode` parameter which later on the `Build()` method of [ByProjectKeyProductProjectionsSearchPost](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Sdk.Api/Generated/Client/RequestBuilders/ProductProjections/ByProjectKeyProductProjectionsSearchPost.cs)  serialized and added as a content with `application/json` type. However based on [documentation ](https://docs.commercetools.com/tutorials/curl-cheatsheet#full-text-search-on-product-projections)body of the post request should be encoded in `application/x-www-form-urlencoded`.Because of this this method works not properly. 

**To Reproduce**
Call POST method and pass serialized to `JsonElement` object with property limit set as 1
API still returns 20 items, like by default.

**Expected behavior**
API should return single item
**Screenshots/Code snippet**
If applicable, add screenshots or code samples to help explain your problem.

**Stack information (please complete the following information):**
 - dotnet: Core 3.1
 - SDK: v1.5.0

**Additional context**
As it should be of content type of `application/x-www-form-urlencoded` it make sense to use `QueryString` of the request and add it as Content with a content type `application/x-www-form-urlencoded` and clean up `QueryString` of the request. As well it seems that `JsonElement? jsonNode` of the `Post()` method is not required in such case. And finally instead of returning `JsonElemen`t from the `ExecuteAsync()` of [ByProjectKeyProductProjectionsSearchPost](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Sdk.Api/Generated/Client/RequestBuilders/ProductProjections/ByProjectKeyProductProjectionsSearchPost.cs)  It make sense to return `IProductProjectionPagedSearchResponse` like Get method returns.
Here a part of `ByProjectKeyProductProjectionsSearchPost` which should be used instead existing one
```
public async Task<IProductProjectionPagedSearchResponse> ExecuteAsync()
{
    var requestMessage = Build();
    return await ApiHttpClient.ExecuteAsync<IProductProjectionPagedSearchResponse>(requestMessage);
}

public override HttpRequestMessage Build()
{
    var request = base.Build();
    request.Content = new FormUrlEncodedContent(QueryParams);
    return request;
}
```

**Comment by jenschude** [comment]
Updated the generator to correctly support form parameters. Result looks now like this:

https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/46bc2cfd0b5934751cdb02312365def9ba7bc4a1/commercetools.Sdk/commercetools.Sdk.Api/Generated/Client/RequestBuilders/ProductProjections/ByProjectKeyProductProjectionsSearchPost.cs

**Comment by jenschude** [comment]
Just issued a new release 2.0.0
