### ISSUE TITLE
missing Discription in PaymentDraft 

### ISSUE THREAD

**Issue by OlofMoriya** [commercetools/commercetools-dotnet-core-sdk-v2#114]
The field Description on the PaymentDraft or PaymentMethodInfo is not part of the sdk but there is a field in the merchant center to display it. 

**Expected behavior**
It should be possible to add a description for the payment method when creating the payment. 

**Screenshots/Code snippet**
![image](https://user-images.githubusercontent.com/13721900/143839009-12c9eb88-134c-4a3a-8090-0166b042cb01.png)

**Comment by jenschude** [comment]
Actually I don't know which field of the payment models this represents as according to the docs there is no description field in payments at all. But the fields specified here https://docs.commercetools.com/api/projects/payments are supported.

**Comment by debwebdanmark** [comment]
> Actually I don't know which field of the payment models this represents as according to the docs there is no description field in payments at all. But the fields specified here https://docs.commercetools.com/api/projects/payments are supported. Most likely description is the field `interfaceText` in [PaymentStatus](https://docs.commercetools.com/api/projects/payments#paymentstatus)

Can comfirm that the interfaceText is the field that is shown in Description

**Comment by jenschude** [comment]
Closing this issue as it's a mismatch between Merchant Center UI and naming in the docs/SDK
