### ISSUE TITLE
Add ContainerAndKey field to UserProvidedIdentifiers

### ISSUE THREAD

**Issue by Vamic** [commercetools/commercetools-dotnet-core-sdk-v2#117]
**Is your feature request related to a problem? Please describe.**
When a custom object is updated, a message gets sent for key-value-document but the ContainerAndKey field is missing from UserProvidedIdentifiers despite existing in the payload.

**Describe the solution you'd like**
ContainerAndKey field added.

**Additional context**
https://docs.commercetools.com/api/message-types#containerandkey

![image](https://user-images.githubusercontent.com/6871222/146504626-8c08521c-df90-43cf-9d7f-c2c62e4e46aa.png)

**Comment by jenschude** [comment]
This should be part of the versions 3.0+

Thx for the report
