### ISSUE TITLE
When trying to get a list of Baskets for a Store return a useful type (not object)

### ISSUE THREAD

**Issue by BielsasBucket** [commercetools/commercetools-dotnet-core-sdk-v2#121]
**Is your feature request related to a problem? Please describe.**
I am trying to get a list of baskets for a store, using `ByProjectKeyInStoreKeyByStoreKeyCartsGet` but the `ExecuteAsync()` returns a `Task<Object>`

**Describe the solution you'd like**
I would like this to return a `ICartPagedQueryResponse` like for `ByProjectKeyCartsGet`

**Describe alternatives you've considered**
I have tried casting the object returned to a `ICartPagedQueryResponse` as that is what it is (or looks very similar) but no good. This is effecting my ability to upgrade

**Additional context**
none

**Comment by BielsasBucket** [comment]
Created a pull request with what I think is needed. https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/pull/123

This is urgent for us, so speedy review/resolution would be most welcome

**Comment by jenschude** [comment]
Triggered the release. Should be available in some minutes

Please see https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/releases/tag/2.2.0
