### ISSUE TITLE
Common interface for ApiMethods

### ISSUE THREAD

**Issue by xferra** [commercetools/commercetools-dotnet-core-sdk-v2#126]
**Is your feature request related to a problem? Please describe.**

Hello,
I'm in the progress of migrating from v1 to v2.
When using v1 I was able to perform generic operations on different Objects using CommandBuilder<>. As for now - different API methods have their own (the same) implementation for Query, Limit, Offset, etc., and there is no common interface for that.

Example:
[Carts.Limit](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/ecc50189cc277ddd07f2c04dbded8c4a4ac39835/commercetools.Sdk/commercetools.Sdk.Api/Generated/Client/RequestBuilders/Carts/ByProjectKeyCartsGet.cs#L77)
[Order.Limit](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/ecc50189cc277ddd07f2c04dbded8c4a4ac39835/commercetools.Sdk/commercetools.Sdk.Api/Generated/Client/RequestBuilders/Orders/ByProjectKeyOrdersEditsGet.cs#L67)

**Describe the solution you'd like**
Introduce an interface for Expand, Sort, Limit, Offset, etc., and if possible for ExecuteAsync too.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by jenschude** [comment]
With 26e4fc2 we introduced now common interfaces. Will be added to the next release

**Comment by csi-lund** [comment]
@jenschude are there any plans for a similar common interface for the post and delete ApiMethods to enable generic operations in a similar vein to above? Also a common interface for the Updates and their repsective actions - I see a IResourceUpdate IResourceUpdateAction interface but its only applied to IChannelUpdate.

**Comment by jenschude** [comment]
With the next release the SDK will include some Interfaces which includes parameters like Sort, Limit etc.

Please see

https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/commit/40358f7a8258e56bfe30f5e9d0b9db80535965d9

Manual written ones like ById, ByGet etc will come in a later release

**Comment by jenschude** [comment]
3.2.0 with this change has been released
