### ISSUE TITLE
A bug happens when a cart set shippingAddress

### ISSUE THREAD

**Issue by lance-rb2** [commercetools/commercetools-dotnet-core-sdk-v2#129]
**Describe the bug**
The field "POBox" don't be saved when a cart set shippingAddress. The other fields of address are ok.

**To Reproduce**
a cart set shippingAddress.

**Expected behavior**
The value of "POBox" should be stored.

**Screenshots/Code snippet**
![image](https://user-images.githubusercontent.com/89450063/151503578-9912a7ef-d914-42ce-8c1b-a2a7d2ed614f.png)
![image](https://user-images.githubusercontent.com/89450063/151504951-68a956fd-bd4a-4181-83a4-34a34d1dbe49.png)
![image](https://user-images.githubusercontent.com/89450063/151505211-e35aa0ef-bff7-436c-839b-598f490da26d.png)

**Stack information (please complete the following information):**
 - dotnet: Core 3.1
 - SDK: v2.0、v2.3

**Additional context**

**Comment by jenschude** [comment]
Nice catch!

Seems that the naming of the json field clashes with the default camel case naming policy. I opened a PR which adds a manual field name mapping to fix the issue

**Comment by jenschude** [comment]
Fixed with version 2.4.0

**Comment by lance-rb2** [comment]
Nice
