### ISSUE TITLE
Configuring a Proxy for the HttpClient

### ISSUE THREAD

**Issue by mortenbock** [commercetools/commercetools-dotnet-core-sdk-v2#140]
The SDK has taken the responsibility of creating the HttpClient used for the API communication.

It would be nice with an option to set a proxy server for this client, and I cannot see how that would be possible with the current implementation.

https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/84f6a8c91fc58fa964dd09d071dccdb5632aa978/commercetools.Sdk/commercetools.Base.Client/DependencyInjectionSetup.cs#L92

The use case would for example be a corporate proxy, or it could be for debugging purposes, to see the actual http calls going through Fiddler.

**Comment by jenschude** [comment]
As the example shows the SetupClient method returns a IHttpClientBuilder instance and allows all options to configure the client to be created.

I added a test showing the configuration of a proxy in 76a7590

Sorry for the inconvenience of the late answer.
