### ISSUE TITLE
It does not work about sorting by scopedPrice in ProductProjectionSearch

### ISSUE THREAD

**Issue by lance-rb2** [commercetools/commercetools-dotnet-core-sdk-v2#143]
**Describe the bug**
It does work about sorting by scopedPrice in ProductProjectionSearch

**To Reproduce**
1. set PriceCustomerGroup、PriceCurrency、PriceCountry、PriceChannel for ProductProjectionSearch 
2. set sort to **variants.scopedPrice.value asc**
3. call the ProductProjectionSearch 

**Expected behavior**
the result of ProductProjectionSearch can be sorted by scopedPrice

**Screenshots/Code snippet**
![image](https://user-images.githubusercontent.com/89450063/161936661-ea3fb093-0982-443a-b220-9942f6998fc7.png)
![image](https://user-images.githubusercontent.com/89450063/161936780-ca4f152a-18ff-4533-ad95-d57c33a561ce.png)
![image](https://user-images.githubusercontent.com/89450063/161936841-7cd246ab-960a-43ed-b948-6931c8e158e7.png)
![image](https://user-images.githubusercontent.com/89450063/161937848-44ce732d-21bc-4c7b-b5cb-69b0f0d6bd85.png)
the result responses some products including scopedPrice but the sort of products is invalid.

**Stack information (please complete the following information):**
 - dotnet: Core 3.1
 - SDK: v2.4.0

**Additional context**

**Comment by lance-rb2** [comment]
Hello, could the products be sorted by scopedPrice in ProductProjectionSearch?

**Comment by MicheleRezk** [comment]
Hello @lance-rb2 , I think you have to adjust the sort expression to be like:
variants.scopedPrice.value.centAmount instead of variants.scopedPrice.value
I tried it on [api playground](https://impex.europe-west1.gcp.commercetools.com/playground ) and it's working

**Comment by lance-rb2** [comment]
Thanks. I had tested it successfully. It was my fault. You can close this issue
