### ISSUE TITLE
Common interface for update actions and RequestBuilders.

### ISSUE THREAD

**Issue by csi-lund** [commercetools/commercetools-dotnet-core-sdk-v2#152]
**Is your feature request related to a problem? Please describe.**

Hi commercetools devs! Firstly thanks for great new SDK, like it 👍 

I'm in the progress of migrating from v1 to v2 and come across a few situations with the generated models and builders where in v1 I was able to write extensions and execute generic operations using UpdateAction<T> etc.  Now things like the model updates XUpdateAction and XUpdate are separate.  As are the Get, Post, and Delete builders with their ById and ByKey variations.

You seem to have already done some of this in https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/issues/126
I see that you introduced the IPagedQueryResourceRequest and IRequestCommand for the paged get commands.
I can see also the IRequestCommand interface is applied to the ByProjectKeyCartsByIDGet. 
I can also see the presence of IResourceUpdate IResourceUpdateAction interfaces but its only applied to IChannelUpdate/IChannelUpdateAction

**Describe the solution you'd like**

Expand IRequestCommand usage to all get, update and delete and their ByKey and ById request builders. where not already applied 
Expand IResourceUpdate IResourceUpdateActions to all Update/UpdateAction models where not already applied.

**Describe alternatives you've considered**
At the moment it would mean writing builder specific extensions but Execute is not exposed so changing the extensions to work differently to accept a function<T> where T : IBaseResource 

**Additional context**
None.

Thanks!

**Comment by jenschude** [comment]
Updates and their Actions now have a shared interface

https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/pull/157/files

Also the SDK will introduce interfaces with the shared query parameters like Sort, Limit etc. Please see
https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/pull/158/files

The ExecuteAsync method is now exposed through the IApiMethod interface

**Comment by jenschude** [comment]
3.2.0 with this change has been released

**Comment by csi-lund** [comment]
Super! thanks for this.
