### ISSUE TITLE
Notification event serialization problem on attributes ?

### ISSUE THREAD

**Issue by NicolasREY69330** [commercetools/commercetools-dotnet-core-sdk-v2#155]
**Describe the bug**
Hi, I just noticed that when getting "stringified" event from Azure Service Bus after it has been pushed by CT, I got an invalid JSON payload 
See example of a `ProductPublished ` type with just the part of the `attributes` having a missing curly brace 

```json
{
  "attributes": [
    {
      "name": "bundled_products",
      "value": [
        {
          "typeId": "product",
          "id": "e3b0f02e-0484-4989-a9b6-dcbc32a****"
        },
        {
          "typeId": "product",
          "id": "c3671846-8d3a-4d5d-b2d9-55653530****"
        }
      ]
    },
    {
      "name": "summary",
      "value": {
        "it": "My super product"
      }
    },
    {
      "name": "size",
      "value": {
        "key": "one_size",
        "label": "One size"
      }
    },
    {
      "name": "weight",
      "value": 2
    },
    {
      "name": "product_classification",
      "value": {
        "key": "NONE",
        "label": {
          "fr": "",
          "it": "",
          "fr-FR": "",
          "es": "",
          "en-US": "Regular product",
          "pt": "",
          "da": ""
        }
        <========  ******************** closing curly brace is missing here ******************
    },
    {
      "name": "related_accessories",
      "value": [
        {
          "typeId": "product",
          "id": "49e96f8b-8c74-4ef9-a3b4-ecdd3f1e****"
        },
        {
          "typeId": "product",
          "id": "2b94910d-cc11-4755-92ca-4eafbcb5****"
        },
        {
          "typeId": "product",
          "id": "751d9739-be25-4b0b-b4bc-ec39a6c7****"
        },
        {
          "typeId": "product",
          "id": "2151faf3-6ff8-4093-9034-345a84f7****"
        },
        {
          "typeId": "product",
          "id": "552c2604-a1f8-4b0f-bf43-757a2af2****"
        },
        {
          "typeId": "product",
          "id": "e0f2ea30-bece-44cb-a2db-4e2a7c2c****"
        }
      ]
    }
  ]
}
```

Curiously it seems not to impact the Deserialization (hydrating a typed object) from this string which is strange to me.

**To Reproduce**
Typically in the Azure Service Bus message handler

```C#
      private async Task MessageHandler(ProcessMessageEventArgs args)
        {
            string body = args.Message.Body.ToString();
            _logger.LogInformation(body);
         }
```

Please PM me if you need to access our specific account / data.
Thank you

**Expected behavior**
A valid JSON format

**Screenshots/Code snippet**
If applicable, add screenshots or code samples to help explain your problem.

**Stack information (please complete the following information):**
 - dotnet: [e.g. 6.0]
 - SDK: [e.g. v3.1.0]

**Comment by jenschude** [comment]
The Azure Service Bus instrumented by the API. The issue itself is not related to the SDK. Could you please open a Support Ticket? https://support.commercetools.com

**Comment by jenschude** [comment]
Or is this happening when serializing an Object instance of ProductPublished?

**Comment by NicolasREY69330** [comment]
@jenschude you're right it seems not related to the .net sdk as it's just after I pull the data from ASB.
And as the snippet shows I didn't do anything, just get the body as string and log it.

What I don't understand is why the serializing part (using .net sdk) coming just after is working with a non valid json. 
I'm going to check with the logger part, just in debug to see what the string looks like before any log operation

**Comment by NicolasREY69330** [comment]
@jenschude 
OK I just tested : 
1) the incoming string variable IS a valid Json
2) If I Log it using Serilog : it produces an **invalid** Json 
3) if I log it using Console.WriteLine : it produces a valid Json

Apologies for the lost time, the problem is definitively not related to CommerceTools.
I'll have to understand why serilog produces invalid Json now, but it's another story
Thx u anyway
