### ISSUE TITLE
Mismatch in type

### ISSUE THREAD

**Issue by csi-lund** [commercetools/commercetools-dotnet-core-sdk-v2#166]
Hi IBaseResources and their respective updates are using Int64 version numbers.
However the OrderEditApply is still using Int32 which results in a need to convert when applying an order edit. Whilst this is _unlikely_ to ever be an issue, would be nice if they were aligned and I couldn't find reference to a limit on versions 😝!

>   [DeserializeAs(typeof(commercetools.Sdk.Api.Models.OrderEdits.OrderEditApply))]
    public partial interface IOrderEditApply
    {
        int EditVersion { get; set; }
        int ResourceVersion { get; set; }
    }

**Comment by jenschude** [comment]
Thanks for the report.

The fix has been released with v4.1.0
