### ISSUE TITLE
Exception logged but not thrown from the ExecuteAsync

### ISSUE THREAD

**Issue by codewode** [commercetools/commercetools-dotnet-core-sdk-v2#169]
In the implementation of one of my services, I am creating a client that takes an existing token and invokes call for different resources. In-case the token is not valid then an exception is logged, but ExecuteAsync does not throws exception. Whereas, the behaviour  is different if the service instead of creating a new client  injects an existing client then exceptions are logged and thrown also from ExecuteAsync. Here is an example implementation. What can I do to get catch the exception in my service and map that to custom excpetion?

``` return new ClientContainer()
      {
        Client = ClientFactory.Create(
          "MeClient",
          this.clientConf,
          this.httpClientFactory,
          this.serializerService,
         new AnonymToken(aToken))
      };


ClientContainer.Client.WithApi("my-project-key").Me().Carts().Get().ExecuteAsync()
```

**Comment by jenschude** [comment]
Also i didn't completely understood your problem. I try to give some insights to the SDK client.

The client utilizes a middleware approach. E.g. the Authorization is injected an [AuthorizationMiddleware](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Base.Client/Middlewares/AuthorizationMiddleware.cs). This middleware just adds he AuthHeader to the request. The TokenProvider which seems to be in your case the AnonymToken has to return a Token and/or refresh it in case it's expired.

The [DependencyInjectionSetup](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/413f235581031fd247e87e278ed5ff7c7da449dc/commercetools.Sdk/commercetools.Base.Client/DependencyInjectionSetup.cs#L92-L112) class sets up a HttpClient instance with some DelegatingMessageHandlers which will be instantiated in the ClientFactory. There you will find this line:
https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/413f235581031fd247e87e278ed5ff7c7da449dc/commercetools.Sdk/commercetools.Base.Client/DependencyInjectionSetup.cs#L108

The [ErrorHandler](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Base.Client/ErrorHandler.cs) will convert all responses with a StatusCode greater or equals 400 to an Exception. This should be what you are asking for in case you wanna use a custom configured HttpClient.

**Comment by codewode** [comment]
> 

Thanks @jenschude  for your reply. I must admit that I am not a C# expert. I must be doing something differently. Here is my situation and I believe I must be doing something wrong, so I have created a sample project in-case you would like to try that out.

https://github.com/codewode/commercetools-anonym-token


what am I trying to achieve is, everytime a customer requests to create a cart, then it will generate token, that token will be used in the subsequent requests to update/get the cart. I expect that, if the given token is expired/invalid, then it will throw 401 exception, however I am always getting an empty cart with 200 OK Response. I have also attached postman collection.

**Comment by codewode** [comment]
I certainly missed the point from the docs, after adding SetupClient, it got fixed.

```        
          services.SetupClient(
                "MeClient",
                errorTypeMapper => typeof(ErrorResponse),
                s => s.GetService<SerializerService>()
            );
```
