### ISSUE TITLE
Payment entity : from 4.0.0 to 4.1.0 : missing field

### ISSUE THREAD

**Issue by NicolasREY69330** [commercetools/commercetools-dotnet-core-sdk-v2#174]
Hi,

We've just updated my dependencies, and we noticed that for the entity Payment (generated), a field (`AmountAuthorized`) previously available (in 4.0.0) is now missing, 'breaking changing' one of our developer code.

v 4.0.0
https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/413f235581031fd247e87e278ed5ff7c7da449dc/commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Payments/IPayment.cs#L36

v4.1.0
https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/4.1.0/commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/Payments/IPayment.cs

If I rely to the [current API documentation](https://docs.commercetools.com/api/projects/payments#payment) this is what is expected, but when I make a raw call to the API the field is still returned
![image](https://user-images.githubusercontent.com/50946960/182139712-75332aea-30f1-40ce-8e8d-d4a1b0f840af.png)

I guess it's for compatibility reason, but I wonder how the deprecated field was filled in before v4.1.0, is it the same value for the `AmountPlanned` field and for the removed `AmountAuthorized` field ? 
Is it something possible to decorate future discarded fields as [Deprecated] to know if we could rely on it for a long period or not ?

Thank you for your help

**Comment by jenschude** [comment]
Oh sorry. It should have been gone already with the 4.0.0. There is no replacement field for it as it had been deprecated already when payment endpoint was going out of Beta. Seems that we missed here to add the obsolete attribute.

For similar functionality either use a custom field or store the information in the transactions or interface interactions.

**Comment by NicolasREY69330** [comment]
Thank you, we'll see if we can get rid of it in our own process.
I close the ticket for now 👍
