### ISSUE TITLE
Missing description in lineItem

### ISSUE THREAD

**Issue by de-burhan** [commercetools/commercetools-dotnet-core-sdk-v2#176]
**Describe the bug**
LineItem has product name, product key but missing product description

**Expected behavior**
LineItem has LocalizedString description

**Stack information:**
 - dotnet: [e.g. Core 3.0]
 - SDK: [e.g. v2.2]

**Comment by jenschude** [comment]
This is not an issue of the SDK as the API is not providing this information. Please see https://docs.commercetools.com/api/projects/carts#lineitem

You can open a feature request for this at our support portal https://support.commercetools.com
