### ISSUE TITLE
ProductSelections

### ISSUE THREAD

**Issue by csi-lund** [commercetools/commercetools-dotnet-core-sdk-v2#182]
More of question than a bug.

I noticed that the ProductSelections are not available on the projectApiRoot.
I know its a beta feature so just wanted to check if this was intentional?

Thanks in advance!

**Comment by jenschude** [comment]
Not intentional but the ProjectApiRoot is not automatically generated so it has to be put there. As a workaround you could use:

```

**Comment by csi-lund** [comment]
with() was private iirc - ive just injected the client and projectapiroot together and initalised the apiroot with its key to access it for now

**Comment by jenschude** [comment]
Thanks 👍 

I also made the with method public and released the 5.1.1
