### ISSUE TITLE
Example Console App fails with BadRequest

### ISSUE THREAD

**Issue by wehnertb** [commercetools/commercetools-dotnet-core-sdk-v2#186]
**Describe the bug**
I build the commercetools.Api.ConsoleApp in commercetools.Sdk\Examples and when I run the app (after providing my credential information (including AuthorizationBaseAddress and ApiBaseAddress) - I get a 404 error.

**To Reproduce**
Put valid credentials into the ClientConfiguration Object, build the app, run the app

**Expected behavior**
I would expect it to connect to my CT instance and provide information

**Screenshots/Code snippet**

**Stack information (please complete the following information):**
 - dotnet: Core 3.1
 - SDK: 5.1.1

**Additional context**

**Comment by jenschude** [comment]
Could you please try to replace the API call with this block?

```
            try
            {
                var project = await new ApiRoot(client)
                    .WithProjectKey(config.ProjectKey)
                    .Get()
                    .ExecuteAsync();
                Console.WriteLine(project.Name);
            }
            catch (BadRequestException e)
            {
                Console.WriteLine(e.Body);
            }
```

So you get more detailled information about the BadRequest.

**Comment by wehnertb** [comment]
It looks like I was using an older version of the SDK (3.2) - once I upgraded to 5.1.1 the problem went away and worked as expected.

**Comment by jenschude** [comment]
Perfect thanks for the update
