### ISSUE TITLE
Question About Creating Subscriptions

### ISSUE THREAD

**Issue by glennsdavis** [commercetools/commercetools-dotnet-core-sdk-v2#188]
IDestination has been obsoleted in the SDK. What replaces Destination when creating a subscription? How would I specify a connection string for an Azure Service Bus for my subscription? Thanks.

public class SubscriptionDraft : ISubscriptionDraft
{
    public List<IChangeSubscription> Changes { get; set; }

    [Obsolete]
    public IDestination Destination { get; set; }

    public string Key { get; set; }

    public List<IMessageSubscription> Messages { get; set; }

    public IDeliveryFormat Format { get; set; }
}

**Comment by jenschude** [comment]
Actually I'm wondering too.

Checking where the annotation came from.

**Comment by jenschude** [comment]
Released 5.2.1 with a fix. Still investigating why it was marked obsolete.

**Comment by jenschude** [comment]
After the code is generated we run dotnet format on the codebase. And for some reason this added the link obsolete flag.

**Comment by glennsdavis** [comment]
Thank you for the quick response.
    On Tuesday, November 1, 2022 at 02:07:30 PM PDT, Jens Schulze ***@***.***> wrote:  
 
 


After the code is generated we run dotnet format on the codebase. And for some reason this added the link obsolete flag.

**Comment by jenschude** [comment]
Version 5.2.2 fixed the formatter issue. Should not occur anymore.

Thanks for the report
