### ISSUE TITLE
CentPrecisionMoney conversion mismatch

### ISSUE THREAD

**Issue by ekorkutvaltech** [commercetools/commercetools-dotnet-core-sdk-v2#194]
Hello, I'm migrating the SDK usage in our solution from v1 to v2. However I'm noticing some of our units tests fail when converting decimal to/from CentPrecisionMoney type.

**Describe the bug**
It seems the _FromDecimal_ + _AmountToDecimal_ usage ends up with an invalid amount in SDK v2.

**To Reproduce**
```
// SDK v1
var money1 = commercetools.Sdk.Domain.Money.FromDecimal("EUR", 75); // -> centAmount:7500, currencyCode:"EUR", type:CentPrecision, fractionDigits:null
var amount1 = money1.AmountToDecimal(); // -> returns 75

// SDK v2
var money2 = commercetools.Sdk.Api.Models.Common.CentPrecisionMoney.FromDecimal("EUR", 75); // -> centAmount:7500, currencyCode:"EUR", type:"centPrecision", fractionDigits:0
var amount2 = commercetools.Sdk.Api.Models.Common.TypedMoneyExtensions.AmountToDecimal(money2); // -> returns 7500 instead of 75
```

**Expected behavior**
I'd expect the original amount that was used when creating the money type should be returned.

**Screenshots/Code snippet**
N/A

**Stack information (please complete the following information):**
 - dotnet: .NET 6
 - SDK: v5.3.0

**Comment by jenschude** [comment]
I opened a PR with a fix as the `fromDecimal` was not setting the fractionDigits. Additionally added `ToDraft` helper methods.
