### ISSUE TITLE
Quotes: quoteState missing  from IQuote in commercetools.Sdk.Api.Models.Quotes

### ISSUE THREAD

**Issue by Tarostar** [commercetools/commercetools-dotnet-core-sdk-v2#200]
**Describe the bug**
I am not sure if this is a bug, but QuoteState is missing from IQuote in commercetools.Sdk.Api.Models.Quotes. I get it as part of the reply when doing a GET to {{host}}/{{project-key}}/quotes.

**Stack information (please complete the following information):**
 - SDK: .Net 5.1.1, 5.30 and 6.0.0

**Additional context**
I need to get the quote state, e.g: "Pending", "Declined", "Accepted", etc.

**Comment by jenschude** [comment]
Opened an issue in the upstream repository

**Comment by Tarostar** [comment]
> Opened an issue in the upstream repository

Could you give me a link to the upstream repo where this is posted? I can't find it and would like to keep track of when this gets resolved. Thanks.

**Comment by jenschude** [comment]
Sorry for the late reply.

The fix had been released with version 6.1.0.

I can't post a link to the upstream repository as it's a private one.
