### ISSUE TITLE
Question about Serialization/Deserialization of messages

### ISSUE THREAD

**Issue by NicolasREY69330** [commercetools/commercetools-dotnet-core-sdk-v2#203]
Hi,

We store in our own event stream (Kafka) commerce tools messages triggered from Azure Service Bus, most of them have been serialized using the v4.0.0 version of the CT .net client and the supplied CT serializer as recommended.

Will these stored json string be deserializable out of the box regardless of the new versions (5.x and 6.x and even above) ? In other word, can we update the library transparently ?

This is crucial for our activity to be able to deserialize events that has been stored with previous versions, to handle new needs, obviously if we want to be up to date with your nuget package, we'll mix events serialized with different versions.

Thanks for your help

**Comment by jenschude** [comment]
The serialization of a model should write the same JSON as like as it's coming from the API. So deserialisation should not be of an issue here.

But the SDK progresses as the API progresses. Sometimes there are deprececations, removals or changes which are backwards compatible on the JSON level, but require a backwards incompatible change regarding the SDK types. These are typically the reasons for a new major version.

**Comment by NicolasREY69330** [comment]
Thanks for the reply.
If I understand well the types may/will change in the SDK because the API provides new fields, adding breaking changes that makes the SDK jump to a new major version, but a JSON, regardless of the SDK version that serialized it, will always be deserializable, on any SDK version, but new properties will be skipped if they are not part of the SDK version that makes the deserialization, and the provided types will obviously as the  SDK version knows them, is it correct ?

My main concern here is : we don't want the deserialization operation to crash let's say if we serialize with v4.0.0 and deserialize the same JSON with the 6.0.0 (or above)

**Comment by jenschude** [comment]
I think a small gotcha can happen here. Assuming you are serializing with a 4.0.0. It deserializes the API response with a field unknown to the SDK. This one will be omitted. And when you now serialize it to Kafka it will be lost and can't be recovered anymore, even with a newer SDK version. Nevertheless a newer version of the SDK should not crash. This is also one of the reasons we didn't used Enums directly to be forward compatible.

Only thing what should be looked at if a type may have been renamed, dropped in a major version update. Especially as with the recent changes in the pipeline we are able to give more information about these kind of changes in release notes.

**Comment by NicolasREY69330** [comment]
Ok, I think one possible solution, to avoid new field loss could be to also store in the Kafka event, the raw JSON string from the event coming from ASB, then regardless of the SDK, the deserialization could always been done with all new fields available.

**Comment by jenschude** [comment]
Btw if you directly write to Kafka and process messages in subscribers. In order to avoid this scenario i would create take the client instance and use the ExecuteAsJsonAsync method to retrieve the pure json and write it directly.


```
// in pseudo code
CtpClient client = ...
String json = await client.ExecuteAsJsonAsync(projectApiRoot.Messages().Get().Build())
```

**Comment by NicolasREY69330** [comment]
We need to unserialize the coming message, to handle country filtering (1 CT instance handling multi country, with 1 K8S environment per country, having its dedicated Kafka per country). 
It supposes we read the content of the message, make some filtering based on its fields + sometimes query CT API to get extra information to route it properly. But at this time this the deserialized message (from the CT SDK version x.x.x) that we pushed to Kafka (serialized with the CT SDK serializer). 
Here we can obviously loose new properties, that we currently don't need but that could be useful in the future

**Comment by jenschude** [comment]
Yes totally. Best would be here to work with the deserialized json, but write the raw json to the queue. Most likely will safe you from a lot of pain in the future.

And we never know if there is subtile bug hidden somewhere.

**Comment by NicolasREY69330** [comment]
Ok we'll prioritize this approach then. Thank you for your help
