### ISSUE TITLE
Product exists HEAD call support

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-dotnet-core-sdk-v2#208]
**Is your feature request related to a problem? Please describe.**
We're trying to use https://docs.commercetools.com/api/projects/products#check-existence-of-product-by-key to check if a product exists. The SDK does support executing it, but it will try to JSON deserialize the empty response, resulting in a JsonException.

```
try
{
    await client.WithApi().WithProjectKey(projectKey).Products().WithKey(productKey).Head()
        .ExecuteAsync(cancellationToken);
}
catch (NotFoundException)
{
    return false;
}
catch (JsonException)
{
    return true;
}
```
**Describe the solution you'd like**
An ExecuteAsync that allows empty responses, or something like this:
`bool productExists = await client.WithApi().WithProjectKey(projectKey).Products().WithKey(productKey).Head()
        .ExistsAsync(cancellationToken)`
        
Perhaps I missed the correct way to do this? Cannot figure it out from the tests/code of this repo.

**Comment by jenschude** [comment]
Head methods now deserialize to String. So they are not failing anymore with an JsonException.

Also I added the ExecuteAsJsonAsync, SendAsync and SendAsJsonAsync methods.

The AsJson methods just return the json as String without deserializing them. The Send methods also return the response status code, headers and reason phrase additionally to the Body.
