### ISSUE TITLE
Image upload always missing content type

### ISSUE THREAD

**Issue by PedroCosta93** [commercetools/commercetools-dotnet-core-sdk-v2#209]
When uploading an image via the SDK I get a bad request error every time saying that the Content-Type header is missing (It isn't).
Tried via postman and everything worked just fine.

Here's a code sample:

```
	string path = @"\Images\drainage-pump.jpg";				
        using (FileStream file = new FileStream(path, FileMode.Open))
        {	     
	        ApiHttpHeaders headers = new ApiHttpHeaders();
	        headers.AddHeader(ApiHttpHeaders.CONTENT_TYPE, "image/jpeg");
        
	        List<KeyValuePair<string, string>> queryParams = new();
	        queryParams.Add(new KeyValuePair<string, string>("variant", "1"));
        
	        var result = await projectApiRoot.With().Products().WithId("97353e78-4109-4fc9-952d-a0d3e5971e68").Images().Post(file).WithHeaders(headers).WithQueryParam(queryParams).ExecuteAsync();						      
        }
```

And i get the error: {"statusCode":400,"message":"Missing Content-Type and can't determine image format based on filename: img. The supported formats are image/jpeg, image/png and image/gif.","errors":[{"code":"InvalidInput","message":"Missing Content-Type and can't determine image format based on filename: img. The supported formats are image/jpeg, image/png and image/gif."}]}

Also tried with the AddHeader method instead of WithHeaders. The result is the same.

**Comment by jenschude** [comment]
I released a fix with version 6.3.1

There were two problems. It would have worked with a provided filename. Without the filename the image format is read with the help of the content type header by the API. But the content type has to be set separately in dotnets request instance.
