### ISSUE TITLE
OOTB models in SDK not serializing properly

### ISSUE THREAD

**Issue by chandank-nu** [commercetools/commercetools-dotnet-core-sdk-v2#215]
**Describe the bug**
I have a DOTNET core microservice that is interacting with Commercetools for Cart API. We're exposing various APIs:

- Create cart
- Add line item 
- Add Shipping address etc

Here we are trying to return OOTB model Cart as response but when it is serialized the response only contains fields in the interfaces not the actual implementation of the interfaces. Also, some of the string values are getting converted in Arrays with characters as array elements.
Please take a look at the following response. 
`{
    "id": "99c62e85-6df9-4a28-a934-0eca8468b422",
    "version": 1,
    "createdAt": "2023-02-28T09:50:31.605Z",
    "lastModifiedAt": "2023-02-28T09:50:31.605Z",
    "key": null,
    "lastModifiedBy": {
        "clientId": "8oFHnRy_XSz8ZWa6X1i8NTM7",
        "externalUserId": null,
        "customer": null,
        "anonymousId": "8087f873-9e91-4fbb-9b97-11b87f58be12"
    },
    "createdBy": {
        "clientId": "8oFHnRy_XSz8ZWa6X1i8NTM7",
        "externalUserId": null,
        "customer": null,
        "anonymousId": "8087f873-9e91-4fbb-9b97-11b87f58be12"
    },
    "customerId": null,
    "customerEmail": null,
    "anonymousId": "8087f873-9e91-4fbb-9b97-11b87f58be12",
    "businessUnit": null,
    "store": null,
    "lineItems": [],
    "customLineItems": [],
    "totalPrice": {
        "type": [
            "c",
            "e",
            "n",
            "t",
            "P",
            "r",
            "e",
            "c",
            "i",
            "s",
            "i",
            "o",
            "n"
        ],
        "fractionDigits": 2
    },
    "taxedPrice": null,
    "taxedShippingPrice": null,
    "cartState": [
        "A",
        "c",
        "t",
        "i",
        "v",
        "e"
    ],
    "shippingAddress": null,
    "billingAddress": null,
    "shippingMode": [
        "S",
        "i",
        "n",
        "g",
        "l",
        "e"
    ],
    "shipping": [],
    "inventoryMode": [
        "N",
        "o",
        "n",
        "e"
    ],
    "taxMode": [
        "P",
        "l",
        "a",
        "t",
        "f",
        "o",
        "r",
        "m"
    ],
    "taxRoundingMode": [
        "H",
        "a",
        "l",
        "f",
        "E",
        "v",
        "e",
        "n"
    ],
    "taxCalculationMode": [
        "L",
        "i",
        "n",
        "e",
        "I",
        "t",
        "e",
        "m",
        "L",
        "e",
        "v",
        "e",
        "l"
    ],
    "customerGroup": null,
    "country": null,
    "shippingInfo": null,
    "discountCodes": [],
    "directDiscounts": [],
    "custom": null,
    "paymentInfo": null,
    "locale": null,
    "deleteDaysAfterLastModification": 90,
    "refusedGifts": [],
    "origin": [
        "C",
        "u",
        "s",
        "t",
        "o",
        "m",
        "e",
        "r"
    ],
    "shippingRateInput": null,
    "itemShippingAddresses": [],
    "totalLineItemQuantity": null
}`

**To Reproduce**
Create a dotnet core project and expose an API to Get Cart/Get My Cart.
  `public IActionResult GetMyCart()
        {
            ICart cart = _cartService.GetMyCart();

            if (cart == null) return NotFound();

            return Ok(cart);
        }`

**Expected behavior**
The response should contain all attributes/fields of the Cart model.

**Screenshots/Code snippet**

**Stack information (please complete the following information):**
 - dotnet: [e.g. Core 6.0]
 - SDK: [e.g. v6.1]

**Additional context**

**Comment by jenschude** [comment]
You have to use the SerializerService provided by the SDK. E.g. by using the UseCommercetoolsApiSerialization method.

This will register the necessary Converters to de-/serialize correctly.

**Comment by chandank-nu** [comment]
@jenschude thanks for your response.
I've this already in my Program.cs

`var builder = WebApplication.CreateBuilder(args);
builder.Services.UseCommercetoolsApiSerialization();`

Am I missing something?

**Comment by jenschude** [comment]
When using Ok it's serializing using the default serializer. You have to inject the SerializerService of the SDK into your controller and then use the SerializerService.serialize method.

**Comment by chandank-nu** [comment]
This worked.. Apart from injecting SerializerService I had to replace OK to Content and explicitly set content type as "application/json" to get this to work properly.

@jenschude thanks a lot for your help!!

**Comment by jenschude** [comment]
It should also work with Ok when registering an IActionResultExecutor<JsonResult> handler using the SerializerService

**Comment by chandank-nu** [comment]
@jenschude do you have an example?

**Comment by jenschude** [comment]
Something similar to this one:

https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonResultExecutor.cs

Then register the custom executor:

```
services.AddSingleton<IActionResultExecutor<JsonResult>, CustomJsonResultExecutor>();
```

And in the controller use:

```
return Json(cart);
```

But looking at the executor I assume it's not worth the hassle.
