### ISSUE TITLE
Use ISerializerService in Dependency Injection Setup

### ISSUE THREAD

**Issue by MoritzDa** [commercetools/commercetools-dotnet-core-sdk-v2#221]
**Is your feature request related to a problem? Please describe.**
I want to be able to use the interface `ISerializerService` in constructor injection instead of `SerializerService`, when setting up the SerializerService with Dependency Injection via `services.UseCommercetoolsApiSerialization();`. Then it would also be better for testing and mocking.

**Describe the solution you'd like**
I would like to change the service registration in the DI setup like this:

```diff
- services.AddSingleton<SerializerService>();
+ services.AddSingleton<ISerializerService, SerializerService>();
```

**Describe alternatives you've considered**
Right now I have the current workaround in place to be able to use the interface:
```csharp
service.UseCommercetoolsApiSerialization();
service.AddSingleton<ISerializerService, SerializerService>();
```

**Additional context**
Acutally the expected behaviour was introduced within #23 in commit ([6c04123](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/pull/23/commits/6c0412362e3a4130d30c572115ee9bffb20d12d8)) but, also removed in the same PR with commit ([0ded78e](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/pull/23/commits/0ded78ed3cffbcefd01b761bc4bdef8e7bd83873))

The DI should be the same for: `commercetools.Sdk.Api/DependencyInjectionSetup.cs`, `commercetools.Sdk.HistoryApi/DependencyInjectionSetup.cs`, `commercetools.Sdk.ImportApi/DependencyInjectionSetup.cs` and `commercetools.Sdk.MLApi/DependencyInjectionSetup.cs`

**Comment by jenschude** [comment]
We would more likely have to create a marker interface for each of the SerializerService implementations, as they hold specific configurations for the supported API.

But overall yes we are open for supporting a interface instead of a specific implementation

**Comment by MoritzDa** [comment]
Okay I must say that I don't fully understand the purpose of a marker interface and how and where it is used. But I trust, that you guys know the potential benefits of using it.
So do you think my sugestet idea is any good? Or do you think it should be implemented differently, with the mentioned marker interface? Or not implemented at all?

**Comment by jenschude** [comment]
Just opened a PR which adds the API specific marker interfaces. For backwards compatibility the registration of the SerializerService classes are still there, but internally it will be only retrieved by it's interface.

So it should be possible to mock or replace them e.g. in tests.

**Comment by MoritzDa** [comment]
Hey, perfect! Thank you for the fast implementation. Really appreciate it.

I now understand better what you meant by the marker interfaces. After seeing your changes and implementation.

Just for my understanding:
I now can just use in the DI setup: (when the new version is released)
```csharp
...
services.UseCommercetoolsApiSerialization();
...
```

And the use the marker interface in the constructor for example like this:
```csharp
    private readonly IApiSerializerService _serializerService;

    public ExampleService(IApiSerializerService serializerService)
    {
        _serializerService = serializerService;
    }
```

Thank you a lot again :)

**Comment by jenschude** [comment]
Yes. That's the idea behind it. And for testing purposes you could inject whatever implementation you mark with the interface ;)
