### ISSUE TITLE
Fix Security Vulnerability with System.Text.Encodings.Web

### ISSUE THREAD

**Issue by varun-woolies** [commercetools/commercetools-dotnet-core-sdk-v2#236]
**Is your feature request related to a problem? Please describe.**
We are utilising this Nuget package and SNYK, our security vulnerability scanner has reported a CRITICAL vulnerability with one of the transitive dependencies this package pulls in System.Text.Encodings.Web

See details here https://security.snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTENCODINGSWEB-1253267

**Describe the solution you'd like**
Remove the dependency on the Microsoft.AspNetCore.WebUtilities package that pulls in the vulnerable version of System.Text.Encodings.Web . Alternatively use a newer version of Microsoft.AspNetCore.WebUtilities which references the correct version of System.Text.Encodings.Web that does not have a vulnerability

It looks like your project might be doing a custom build of Microsoft.AspNetCore.WebUtilities and uploading it to `myget` 
[This is the line](https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.WebUtilities/Microsoft.AspNetCore.WebUtilities.csproj#L18C10-L18C10) in the source repo which will need to update the reference to System.Text.Encodings.Web

**Comment by jenschude** [comment]
I refactored the part which uses the WebUtility dependency. So it can be removed as a dependency.

Will soon release a new version of the SDK

**Comment by jenschude** [comment]
https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/releases/tag/8.1.0
