### ISSUE TITLE
LineItems is null but it should not be null. Schema can be outdated

### ISSUE THREAD

**Issue by kcrnac** [commercetools/commercetools-dotnet-core-sdk-v2#259]
Hi,

I am trying to retrieve Orders from CommerceTools by Order IDs and select only specific properties in the result set, such as Id, OrderNumber, TotalPrice, and collection of LineItems. Everything works until I try to include LineItems in the results set after I get the exception: 

> LineItems is null but it should not be null. Schema can be outdated

Essentially, the generated GraphQL query should look something like this (except for the fact that using SDK I am trying to retrieve orders by order IDs, and not all of them)

```
query {
  orders {
    results {
      orderNumber
      id
      totalPrice {
        centAmount
      }
      lineItems {
        productId
      }
    } 
  }
}
```

Actual query using GraphQL Client from SDK
```
var variables = new { filter = $@"id in ({idsFilter})" };

var result = await _client.GetGraphQLClient()
.Query(variables,
           static (i, o) => o.Orders(where: i.filter, selector: r => new
           {
               results = r.Results(order =>
               new OrderDto
               {
                   Id = order.Id,
                   OrderNumber = order.OrderNumber,
                   TotalPrice = new OrderCentPrecisionMoneyDto
                   {
                       CentAmount = order.TaxedPrice(t => t.TotalGross(tt => tt.CentAmount))
                   },
                   LineItems = order.LineItems(null, li => new OrderLineItemDto { ProductId = li.ProductId }).ToList()
               })
           })
);
```
As mentioned before the problem seems to be related to a way how I try to retrieve a collection of LineItems from the Order
```
LineItems = order.LineItems(null, li => new OrderLineItemDto { ProductId = li.ProductId }).ToList()
```
Decompiled implementation of _LineItems_ function from commercetools.Sdk.GraphQL.Api.Order, and supposedly the line that throws an exception, meaning that __LineItems object is indeed NULL

![Screenshot_9](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/assets/6311959/4b87fa13-4798-449d-a7ed-5448aa339576)

I have tried the following:
- Providing Order ID or NULL as an argument to _LineItems_ function
- Retrieve LineItems from _Order.Cart_ property instead, this didn't throw an exception but the LineItems were still NULL

Just a consideration, when I use standard API SDK (non-GraphQL) to retrieve Orders including LineItems, this works as expected, the only difference being that LineItems in that case are of type commercetools.Sdk.Api.Models.Carts (from the Cart), whereas with GraphQL SDK LineItems are of type commercetools.Sdk.GraphQL.Api.LineItem

**Expected behavior**
The expected behavior is that LineItems collection per Order is retrieved from CommerceTools and populated with only ProductId property

**Stack information (please complete the following information):**
 - dotnet: 7
 - commercetools.Sdk.GraphQL.Api 11.2.0

**Comment by kcrnac** [comment]
While writing this ticket I figured out the solution to the problem, but I opened the ticket anyway in case someone else made the same mistake.

The solution to the problem is to NOT use ToList() when trying to map LineItems
```
LineItems = order.LineItems(null, li => new OrderLineItemDto { ProductId = li.ProductId }).ToList()
```
Instead, it should look like this
```
LineItems = order.LineItems(null, li => new OrderLineItemDto { ProductId = li.ProductId })
```
I suppose that calling ToList tries to immediately execute _LineItems_ function which then causes __LineItems property to be NULL at that point because the Query hasn't been executed yet.

**Comment by jenschude** [comment]
The thing to be understood here is that the ZeroQL library does some magic with SourceCode generation. When compiling your project ZeroQL captures calls to the ZeroQL client and compiles them to a string. Therefor the code you write must be static and you only have limited use of dynamic variables.

At runtime the call is not directly executed, but the CallerArgument is used to get the query from the list of compiled queries. After executing the static query only the mapping function is executed.
