### ISSUE TITLE
Filter categories by subtree

### ISSUE THREAD

**Issue by lz039** [commercetools/commercetools-dotnet-core-sdk-v2#270]
Hello,

I found this documentation how to filter categories by subtree.
https://docs.commercetools.com/api/projects/products-search#filter-by-category-subtrees

I'm unsure how to translate this into a where query in the sdk.

works:
masterVariant(categories(id = \"{categoryId}\"))

does not work:
masterVariant(categories(id contains any \"{categoryId}\"))
masterVariant(categories(id in \"{categoryId}\"))

I have a two-level hierarchy and want to filter on the first level.

**Comment by jenschude** [comment]
The filter by category subtrees is only available for the product projection search endpoint.
