### ISSUE TITLE
BadRequest On FailedLogin (Wrong username/password)

### ISSUE THREAD

**Issue by nullableobj** [commercetools/commercetools-dotnet-core-sdk-v2#275]
**Describe the bug**
Throwing bad request when trying to login with wrong credentials. The response is buried in ErrorObject.

**To Reproduce**
Running _client.InStore("storeKey").Login().Post(signInDraft).ExecuteAsync throws BadRequest with StatusCode "InvalidCredentials".

**Expected behavior**
Return null customer object I guess is enough. Or ideally, response with Unauthorized somehow (throw new type of exception call UnAuthorized?)

**Stack information (please complete the following information):**
 - dotnet: [e.g. Core 7.0]
 - SDK: [e.g. v11.2.0]

**Additional context**

**Comment by jenschude** [comment]
I added a helper method to extract the errorcode better. Will be part of the next release:

https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/8090cde8985914b1e88627142459594ccd2021ab/commercetools.Sdk/IntegrationTests/commercetools.Api.IntegrationTests/Customers/CustomersIntegrationTests.cs#L131-L133

**Comment by nullableobj** [comment]
Thanks!

**Comment by jenschude** [comment]
Hi

release 11.4.0 includes the helper already
