### ISSUE TITLE
Inconsistent ApiBaseAddress and AuthorizationBaseAddress format

### ISSUE THREAD

**Issue by MedAnd** [commercetools/commercetools-dotnet-core-sdk-v2#63]
**Describe the bug**
Inconsistent application of BaseAddress format, between ApiBaseAddress and AuthorizationBaseAddress. For example, AuthorizationBaseAddress requires a trailing "/" otherwise an exception is thrown: 

`System.Net.Http.HttpRequestException: 'No such host is known.'`

**To Reproduce**
See code snippet below.

**Expected behavior**
Both the ApiBaseAddress and AuthorizationBaseAddress should either have the trailing "/" character or neither should.

**Screenshots/Code snippet**

![image](https://user-images.githubusercontent.com/13365135/119451494-ac566380-bd78-11eb-8df5-ce296a10e4ce.png)

**Stack information (please complete the following information):**
 - dotnet: [e.g. Core 3.1]
 - commercetools SDK: [e.g. v1.1.4]

**Additional context**
Consider commenting each property of the ClientConfiguration so that during development time the IDE can show hints and examples.

**Comment by MicheleRezk** [comment]
@MedAnd Thanks for reporting this, we were already having RegularExpression Attribute validation for AuthorizationBaseAddress and ApiBaseAddress to make sure urls ends with slash, it was already handled [here](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/15732ab88934890ba71ce35433aff0b075fbe1c0/commercetools.Sdk/commercetools.Base.Client/DependencyInjectionSetup.cs#L73), we also handling it now in ClientFactory and TokenProviderFactory.
