### ISSUE TITLE
Price ValidFrom and ValidTo don't allow nullable values, and hence default to {01/01/0001 00:00:00}

### ISSUE THREAD

**Issue by boro2g** [commercetools/commercetools-dotnet-core-sdk-v2#65]
In the IPriceImport interface, the ValidFrom and ValidTo datetimes force a value, which defaults to 01/01/0001 00:00:00 if you don't set one in your code. This gets imported as 
![image](https://user-images.githubusercontent.com/13680499/120314002-a90c2c00-c2d2-11eb-9d01-afd9bed4d7ce.png)
rather than the values being empty

https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/5dc8fa4da15a351de18e4808d43dcc0f9651853c/commercetools.Sdk/commercetools.Sdk.ImportApi/Generated/Models/Prices/IPriceImport.cs#L19

In the curl examples, if you don't set the ValidFrom or ValidTo they get set as empty / blank

**Comment by boro2g** [comment]
The same thing applies to `ExpectedDelivery` on `IInventoryImport`

**Comment by ashishhk** [comment]
We'll take a look at this issue next

**Comment by boro2g** [comment]
@MicheleRezk @ashishhk  - how are you getting on with the issue? Is it a big one to fix?

**Comment by MicheleRezk** [comment]
@boro2g We're working on it, it will be solved ASAP

**Comment by MicheleRezk** [comment]
@boro2g We solved it and created a new release with version 0.6.0

**Comment by boro2g** [comment]
Great thanks, will give it a test now

**Comment by boro2g** [comment]
![image](https://user-images.githubusercontent.com/13680499/122960512-642c6000-d37b-11eb-8c22-36dd5b5c9223.png)
Version 0.6.0 looks much better - thanks. How do you want to leave the issue, should I close or do you?

**Comment by MicheleRezk** [comment]
@boro2g I just closed it, thanks for reporting this issue
