### ISSUE TITLE
Custom APIM for commercetools config

### ISSUE THREAD

**Issue by theburhan** [commercetools/commercetools-dotnet-core-sdk-v2#68]
**URi segement gets overwritten for ApiBaseAddress**
The URi segement is replaced by the SDK keeping only the domain name.

**To Reproduce**
Define an API gateway and use "ApiBaseAddress" as https://{{domain}}/api/internal-api/commercetools/, at the time of calling the API let's say product projection, then the final URL composed is https://{{domain}}/{{project-key}}/product-projections/search?staged=True.

**Expected behavior**
The URi should take the segements defined in the ApiBaseAddres, so the final URL should be like https://{{domain}}/api/internal-api/commercetools/{{project-key}}/product-projections/search?staged=True.

**Configuration**
```
 "CommercetoolsClient": {
    "AuthorizationBaseAddress": "http://localhost:8090/api/commercetools-auth/",
    "ApiBaseAddress": "http://localhost:8090/internal-api/commercetools/"
  }
```

**Stack information :**
 - dotnet: [e.g. Core 5.0]
 - SDK: [e.g. v2]

**Additional context**
AuthorizationBaseAddress however works fine, the URi segment is not overwritten.

**Comment by MicheleRezk** [comment]
Hello @theburhan,As per [documentation](https://docs.commercetools.com/api/general-concepts), you would select Api Url based on the host Region, so I'm just wondering why would you do a custom API gateway like your example?

**Comment by theburhan** [comment]
Hi @MicheleRezk, I actually want to decouple dotnet service from CT via custom API gateway for two reasons, first, so that in future if for any reason I want to decommission some services from CT in favour of another external system, then dotnet service won't be affected, I will only have to update the APIM with a different target URL, so APIM here is only treated as proxy call.

Also, I will be using mock server for e2e integration tests, where I want to avoid making calls to CT. So, in the config on our test env, i will APIM will be making proxy calls to stubs.

I already tested that flow with SDK1, where it was working fine. Is that really a defect in SDK2 that overwrites the ApiBaseUrl or do you think it is done on purpose because having a custom APIM in this use-case is not a good practice?

**Comment by theburhan** [comment]
and the second case is, my service will be deployed in VNET which has no access to the internet. So, I want to make proxy call.

**Comment by MicheleRezk** [comment]
Hi @theburhan,
I already checked the issue and found that we're not replacing the BaseAddress in the client, it will be same as configured in the appsettings.json, please check attached screenshot while debugging it.

![BaseAddress-SDK-V2](https://user-images.githubusercontent.com/30607195/125255916-3728f880-e2fc-11eb-8bea-249c4c9272d7.jpg)

**Comment by MicheleRezk** [comment]
Hi @theburhan ,

Do you still having an issue or should I close it?

**Comment by theburhan** [comment]
Hi @MicheleRezk 
many thanks for your effort in confirming that, for some reasons, we have decided not to use custom api-gateway, but to call commercetools directly.

So this is no longer an issue, nevertheless like you have mentioned there shouldn't be a problem as the URL's are not written.
