### ISSUE TITLE
Missing types for order set shipping method action

### ISSUE THREAD

**Issue by Glen-Moonpig** [commercetools/commercetools-dotnet-core-sdk-v2#90]
**Is your feature request related to a problem? Please describe.**

Missing types for `OrderSetShippingMethodAction` and `OrderSetCustomShippingMethodAction`.

See [Set ShippingMethod](https://docs.commercetools.com/api/projects/order-edits#set-shippingmethod) and [Set Custom ShippingMethod](https://docs.commercetools.com/api/projects/order-edits#set-custom-shippingmethod).

**Describe the solution you'd like**

Add classes:

```csharp
public class OrderSetShippingMethodAction : IOrderSetShippingMethodAction, IOrderUpdateAction
{
    public OrderSetShippingMethodAction();

    public string Action { get; set; }
    public IShippingMethodResourceIdentifier ShippingMethod { get; set; }
    public IExternalTaxRateDraft ExternalTaxRate { get; set; }
}

public class OrderSetCustomShippingMethodAction : IOrderSetCustomShippingMethodAction, IOrderUpdateAction
{
    public OrderSetCustomShippingMethodAction();

    public string Action { get; set; }
    public string ShippingMethodName { get; set; }
    public ShippingRateDraft ShippingRate { get; set; }
    public ITaxCategoryResourceIdentifier TaxCategory { get; set; }
    public IExternalTaxRateDraft ExternalTaxRate { get; set; }
}
```

**Describe alternatives you've considered**

Adding the types in my own source code.

**Additional context**

**Comment by jenschude** [comment]
https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/OrderEdits/StagedOrderSetShippingMethodAction.cs

**Comment by jenschude** [comment]
Hi,

they are available. But as they are actions for an order edit they are called [StagedOrderSetShippingMethodAction](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/OrderEdits/StagedOrderSetShippingMethodAction.cs) and [StagedOrderSetCustomShippingMethodAction](https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/master/commercetools.Sdk/commercetools.Sdk.Api/Generated/Models/OrderEdits/StagedOrderSetCustomShippingMethodAction.cs)

Hope this helps
