### ISSUE TITLE
How to provide client with an existing bearer token?

### ISSUE THREAD

**Issue by Glen-Moonpig** [commercetools/commercetools-dotnet-core-sdk-v2#95]
**Is your feature request related to a problem? Please describe.**

I see I can create a client using a `ClientCredentialsTokenProvider` and a `PasswordTokenProvider`. What if I already have a bearer token and can skip creating one?

**Describe the solution you'd like**

I want to be able to input an existing bearer token that the client can use for the Authorization header.

**Describe alternatives you've considered**

Not sure...

**Additional context**

**Comment by ijn-kruso** [comment]
Any news on this issue?

**Comment by jenschude** [comment]
I added a test with an example to create a TokenProvider for existing tokens.

https://github.com/commercetools/commercetools-dotnet-core-sdk-v2/blob/56a04962f074fa583f85bf24823ad993fa057e4c/commercetools.Sdk/Tests/commercetools.Sdk.Api.Tests/ClientsFactoryTests.cs#L77-L105

Sorry for the invonvenience of the late reply.
